# Scalars - Rank 0 Tensor
### Same as varaibles, with 1 dim and a type


In [1]:
import torch

In [3]:
x_pt = torch.tensor(25 , dtype=int)
x_pt

tensor(25)

In [4]:
x_pt.shape

torch.Size([])

# Vectors - Rank 1 Tensor

### numpy

In [6]:
import numpy as np

In [12]:
x = np.array([25,2,5], dtype=int)

print(x)
print(len(x))
print(x.shape)
print(type(x))
print(type(x[0]))

[25  2  5]
3
(3,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [13]:
# Transposing 1 D vector - no effect
x_t = x.T
print(x)
print(len(x))
print(x.shape)
print(type(x))
print(type(x[0]))

[25  2  5]
3
(3,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [17]:
# Create & transpose a 2-D vector
y = np.array([[25,2,5]])
y_t = y.T

print(y)
print(y_t)
print(len(y_t))
print(y.shape)
print(y_t.shape)
print(type(y))
print(type(y[0]))

[[25  2  5]]
[[25]
 [ 2]
 [ 5]]
3
(1, 3)
(3, 1)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
# Zero vector
z = np.zeros(3)
print(z)
print(z.T)

[0. 0. 0.]
[0. 0. 0.]


In [26]:
# Calculate L2 Norm (distance from origin of point in 3-D space)
print(np.linalg.norm(x))
print(np.linalg.norm(x_t))

25.573423705088842
25.573423705088842


In [28]:
# Squared L2 Norm - same as xT.X
print(np.dot(x,x))
print(np.dot(x,x_t))

654
654


In [29]:
# Max Norm - largest absolute value
print(np.max([np.abs(x[0]), np.abs(x[1]), np.abs(x[2]) ]))

25


## Vectors using PyTorch

In [20]:
import torch 

In [24]:
x_pt = torch.tensor([[25,2,5]], dtype=float)
print(x_pt)
print(x_pt.transpose)

tensor([[25.,  2.,  5.]], dtype=torch.float64)
<built-in method transpose of Tensor object at 0x10f7049a0>


## Matrix - Rank 2 Tensor

In [32]:
import numpy as np

In [34]:
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [35]:
X.shape

(3, 2)

In [36]:
# Select left column
X[:,0]

array([25,  5,  3])

In [38]:
# select second row
X[1,:]

array([ 5, 26])

In [43]:
# slicing by index
X[0:2,0:2]

array([[25,  2],
       [ 5, 26]])

In [44]:
import torch

In [52]:
X_pt = torch.tensor([[25,2],[5,26],[3,7]], dtype=float)
X_pt

tensor([[25.,  2.],
        [ 5., 26.],
        [ 3.,  7.]], dtype=torch.float64)

In [47]:
X_pt.shape

torch.Size([3, 2])

In [48]:
X_pt[:,0]

tensor([25,  5,  3])

In [49]:
X_pt[2,:]

tensor([3, 7])

In [53]:
torch.linalg.matrix_rank(X_pt)

tensor(2)

## High Rank Tensors

Eg : Rank 4 tensors are common for images : 
<ol>
<li> Number of images in a training batch (Eg :32)
<li> Image Height in pixels
<li> Image width in pixels
<li> Number of colour channels (Eg : 3 for RGB)
</ol>


In [54]:
import torch

In [55]:
images_pt = torch.zeros([32, 28, 28, 3])
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [56]:
torch.linalg.matrix_rank(images_pt)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0