In [3]:
import torch
import numpy as np

In [5]:
# Tensor transposition

# numpy
X = np.array([[25,2],[5,26],[3,7]])
X


array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [6]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [7]:
# Torch
X_pt = torch.tensor([[25,2],[5,26],[3,7]], dtype=float)
X_pt

tensor([[25.,  2.],
        [ 5., 26.],
        [ 3.,  7.]], dtype=torch.float64)

In [8]:
X_pt.T

tensor([[25.,  5.,  3.],
        [ 2., 26.,  7.]], dtype=torch.float64)

In [9]:
# Basic Tensor Arithmetic
# numpy
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [10]:
X +2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [11]:
X+2*3

array([[31,  8],
       [11, 32],
       [ 9, 13]])

In [12]:
# Torch
X_pt = torch.tensor([[25,2],[5,26],[3,7]], dtype=float)
X_pt

tensor([[25.,  2.],
        [ 5., 26.],
        [ 3.,  7.]], dtype=torch.float64)

In [13]:
X_pt +2 *3

tensor([[31.,  8.],
        [11., 32.],
        [ 9., 13.]], dtype=torch.float64)

In [14]:
torch.add(torch.mul(X_pt,3), 2)

tensor([[77.,  8.],
        [17., 80.],
        [11., 23.]], dtype=torch.float64)

In [15]:
# Hadamard Product / Eelemnt-wise product

# numpy
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [17]:
A = X + 2

A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [18]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [19]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [20]:
# Reduction - Sum of all elements in a tensor

X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [21]:
# numpy
X.sum()

68

In [24]:
# Specific Axes
X.sum(axis=0)

array([33, 35])

In [25]:
X.sum(axis=1)

array([27, 31, 10])

In [23]:
# Torch

torch.sum(X_pt)

tensor(68., dtype=torch.float64)

In [26]:
# Axes
torch.sum(X_pt, 0)

tensor([33., 35.], dtype=torch.float64)

In [27]:
# Axes
torch.sum(X_pt, 1)

tensor([27., 31., 10.], dtype=torch.float64)

#### Dot Product

In [30]:
# numpy

x = np.array([25,2,5])
y = np.array([0,1,2])

np.dot(x,y)

12

In [32]:
# Torch - accepts only float

x_pt = torch.tensor([25,2,5], dtype=float)
y_pt = torch.tensor([0,1,2], dtype=float)

torch.dot(x_pt, y_pt)


tensor(12., dtype=torch.float64)