In [1]:
import torch
import numpy as np

In [2]:
A = np.array([[3,4], [5,6], [7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [4]:
b = np.array([1,2])
b

array([1, 2])

In [5]:
np.dot(A,b)

array([11, 17, 23])

In [6]:
A_pt = torch.tensor([[3,4], [5,6], [7,8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [7]:
b_pt = torch.tensor([1,2])
b_pt

tensor([1, 2])

In [8]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [9]:
c_pt=torch.tensor([1])
c_pt

tensor([1])

In [10]:
torch.matmul(A_pt, c_pt)

RuntimeError: size mismatch, got 3, 3x2,1

In [11]:
torch.matmul(A_pt, 5)

TypeError: matmul(): argument 'other' (position 2) must be Tensor, not int