In [2]:
import torch
import numpy as np

### Can be used only for square matrices
#### i.e vector span = matrix range
##### Avoid overdetermination (no single intersection point , > 3 lines)
##### Avoid underdetermination (only one line)

### numpy

In [4]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [5]:
X_inv = np.linalg.inv(X)
X_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [19]:
I = np.dot(X,X_inv)
I

array([[ 1.0000000e+00,  0.0000000e+00],
       [-8.8817842e-16,  1.0000000e+00]])

In [8]:
y = np.array([4, -7])
y

array([ 4, -7])

In [10]:
w = np.dot(X_inv,y)
w

array([-1.,  4.])

In [12]:
np.dot(X,w)

array([ 4., -7.])

### PyTorch

In [14]:
Xt = torch.tensor([[4,2],[-5,-3]], dtype=float)
Xt

tensor([[ 4.,  2.],
        [-5., -3.]], dtype=torch.float64)

In [15]:
Xt_inv = torch.inverse(Xt)
Xt_inv

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]], dtype=torch.float64)

In [20]:
torch.matmul(Xt, Xt_inv)

tensor([[ 1.0000e+00,  1.3323e-15],
        [-1.7764e-15,  1.0000e+00]], dtype=torch.float64)

In [24]:
yt = torch.tensor([4, -7], dtype=float)
yt

tensor([ 4., -7.], dtype=torch.float64)

In [30]:
wt = torch.matmul(Xt_inv, yt)
wt

tensor([-1.0000,  4.0000], dtype=torch.float64)

In [32]:
torch.matmul(Xt,wt)

tensor([ 4.0000, -7.0000], dtype=torch.float64)

### Singular Matrix (rows are multiples of first)

In [34]:
Xt2 = torch.tensor([[-4,-1],[-8,-2]], dtype=float)
Xt2

tensor([[-4., -1.],
        [-8., -2.]], dtype=torch.float64)

In [35]:
Xt2_inv = torch.inverse(Xt2)
Xt2_inv

_LinAlgError: torch.linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.