In [4]:
import numpy as np
import torch

In [2]:
X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [3]:
np.linalg.det(X)

-2.0000000000000004

In [10]:
np.linalg.inv(X)

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [5]:
X_p = torch.tensor([[4,2],[-5,-3]],dtype=float)
X_p

tensor([[ 4.,  2.],
        [-5., -3.]], dtype=torch.float64)

In [6]:
torch.linalg.det(X_p)

tensor(-2.0000, dtype=torch.float64)

In [11]:
torch.linalg.inv(X_p)

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]], dtype=torch.float64)

In [7]:
X_p1 = torch.tensor([[-4,1],[-8,2]],dtype=float)
X_p1

tensor([[-4.,  1.],
        [-8.,  2.]], dtype=torch.float64)

In [9]:
torch.linalg.det(X_p1)

tensor(0., dtype=torch.float64)

In [12]:
torch.linalg.inv(X_p1)

_LinAlgError: torch.linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

### Generalising determinants

In [13]:
X = torch.tensor([[1,2,4],[2,-1,3],[0,5,1]],dtype=float)
X

tensor([[ 1.,  2.,  4.],
        [ 2., -1.,  3.],
        [ 0.,  5.,  1.]], dtype=torch.float64)

In [14]:
torch.linalg.det(X)

tensor(20., dtype=torch.float64)