Eigendecomposition is A = V(upper-lambda>V(inverse))
<br><br>
V is a concatenation of all Eigenvectors of A
<br><br>
(upper-lambda) ia the diagonal matrix (lower-lambda)


In [2]:
import numpy as np

In [25]:
A = np.array([[4, 2],[-5, -3]])
A

array([[ 4,  2],
       [-5, -3]])

In [26]:
lambdas, V = np.linalg.eig(A)
lambdas

array([ 2., -1.])

In [27]:
V

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [28]:
Vinv = np.linalg.inv(V)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [29]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [30]:
np.dot(V, np.dot(Lambda,Vinv))

array([[ 4.,  2.],
       [-5., -3.]])

In [31]:
A

array([[ 4,  2],
       [-5, -3]])

### With real numbers only & Q is orthogonal : A = Q(LAMBDA)Q-Transpose

In [15]:
A = np.array([[2,1],[1,2]])
A

array([[2, 1],
       [1, 2]])

In [16]:
lambdas, Q = np.linalg.eig(A)

In [17]:
lambdas

array([3., 1.])

In [18]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [33]:
# Prove Q is orthogonal : Q-Transpose * Q = Q * Q-Transpose = I

print(np.dot(Q, Q.T))
print(np.dot(Q.T, Q))

[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]


In [20]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [21]:
np.dot(Q, np.dot(Lambda, Q.T))

array([[2., 1.],
       [1., 2.]])

### 3 Dimensional Tensors and pytorch

In [34]:
import torch

In [63]:
P = torch.tensor([[25,2,-5],[3,-2,1],[5,7,4]], dtype=torch.float)
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [64]:
lambdas_cplx, V_cplx = torch.linalg.eig(P)

In [65]:
lambdas_cplx

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [66]:
V_cplx

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [67]:
lambdas = lambdas_cplx.real
lambdas

tensor([23.7644,  6.6684, -3.4328])

In [68]:
V = V_cplx.real
V

tensor([[ 0.9511, -0.2386,  0.1626],
        [ 0.1218, -0.1924, -0.7705],
        [ 0.2837, -0.9519,  0.6163]])

In [69]:
Lambdas = torch.diag(lambdas)
Lambdas

tensor([[23.7644,  0.0000,  0.0000],
        [ 0.0000,  6.6684,  0.0000],
        [ 0.0000,  0.0000, -3.4328]])

In [71]:
Pinv = torch.linalg.inv(P)
Pinv

tensor([[ 0.0276,  0.0790,  0.0147],
        [ 0.0129, -0.2298,  0.0735],
        [-0.0570,  0.3033,  0.1029]])

In [72]:
torch.matmul(P, Pinv)

tensor([[ 1.0000e+00, -8.9407e-08, -5.2154e-08],
        [ 1.1176e-08,  1.0000e+00, -7.4506e-09],
        [-1.4901e-08, -1.1921e-07,  1.0000e+00]])

In [73]:
torch.matmul(P, torch.matmul(Lambdas, Pinv))

tensor([[15.5752, 49.1025, 11.4845],
        [ 1.9898,  7.6586, -0.2856],
        [ 4.6595, -5.4984,  3.7661]])

In [48]:
P

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])