A = UDV-Transpose <br>
- U - Orthogonal m x m , columns are left-singular vecoros of A = eigenvectors of AA-transpose
- V - Orthogonal n x n , columns are right-singular vecoros of A = eigenvectors of A-transposeA
- D - Diagonal m x n , diagonal elemnts are singular values of A

In [1]:
import numpy as np

In [3]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [4]:
U, d , VT = np.linalg.svd(A)

In [5]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [6]:
d

array([8.66918448, 4.10429538])

In [8]:
np.diag(d)

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [7]:
VT # already transposed

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [9]:
# To enable matrix multiplication for A = UDV-transpose, D must be m xn as well
D = np.concatenate((np.diag(d), [[0,0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [10]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

In [11]:
np.matmul(U, np.matmul(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])