A(+) = V D(+) U-transpose
<br> <br>
U , D , V are SVD of A <br>
D(+) = (D with reciprocal of all non-zero elemnts)

In [1]:
import numpy as np

In [3]:
A = np.array([[-1,2],[3,-2],[5,7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [4]:
U, d, VT = np.linalg.svd(A)

In [5]:
U

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [6]:
d

array([8.66918448, 4.10429538])

In [7]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [8]:
D = np.diag(d)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538]])

In [9]:
Dinv = np.linalg.inv(D)
Dinv

array([[0.1153511 , 0.        ],
       [0.        , 0.24364718]])

In [11]:
Dplus = np.concatenate((Dinv, np.array([[0,0]]).T),axis=1)
Dplus

array([[0.1153511 , 0.        , 0.        ],
       [0.        , 0.24364718, 0.        ]])

In [12]:
Aplus = np.dot(VT.T, np.dot(Dplus, U.T))
Aplus

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

# Just use pinv

In [13]:
np.linalg.pinv(A)

array([[-0.08767773,  0.17772512,  0.07582938],
       [ 0.07661927, -0.1192733 ,  0.08688784]])

In [14]:
# Using pytorch
import torch

A_p= torch.tensor([[-1,2], [3,-2], [5,7]], dtype=torch.float64)

torch.pinverse(A_p)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]], dtype=torch.float64)